// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ledswitch = NULL;
lv_obj_t * ui_SG90Button = NULL;
lv_obj_t * ui_Temp = NULL;
// event funtions
void ui_event_ledswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_led_event_func(e);
    }
}

void ui_event_SG90Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        on_servo_button_clicked(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        on_servo_button_clicked(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ledswitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_ledswitch, 219);
    lv_obj_set_height(ui_ledswitch, 105);
    lv_obj_set_align(ui_ledswitch, LV_ALIGN_CENTER);

    ui_SG90Button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SG90Button, 84);
    lv_obj_set_height(ui_SG90Button, 79);
    lv_obj_set_x(ui_SG90Button, -262);
    lv_obj_set_y(ui_SG90Button, 166);
    lv_obj_set_align(ui_SG90Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SG90Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SG90Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temp = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Temp, 150);
    lv_obj_set_height(ui_Temp, 70);
    lv_obj_set_x(ui_Temp, 186);
    lv_obj_set_y(ui_Temp, 165);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Temp, "0");
    lv_textarea_set_placeholder_text(ui_Temp, "Placeholder...");
    lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ledswitch, ui_event_ledswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SG90Button, ui_event_SG90Button, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ledswitch = NULL;
    ui_SG90Button = NULL;
    ui_Temp = NULL;

}
