// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ledswitch = NULL;
// event funtions
void ui_event_ledswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        switch_led_event_func(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED){
        printf("switch value: \n");
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ledswitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_ledswitch, 219);
    lv_obj_set_height(ui_ledswitch, 105);
    lv_obj_set_align(ui_ledswitch, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ledswitch, ui_event_ledswitch, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ledswitch = NULL;

}
