#pragma once

#define GPIO_TURN_LEFT_SET 0
#define GPIO_TURN_RIGHT_SET 1

#define GPIO_TURN_LEFT_BLINK_START 2
#define GPIO_TURN_RIGHT_BLINK_START 3

#define GPIO_TURN_LEFT_BLINK_STOP 4
#define GPIO_TURN_RIGHT_BLINK_STOP 5

#define GPIO_TURN_ALL_BLINK_START 6
#define GPIO_TURN_ALL_BLINK_STOP 7